### ISSUE TITLE
kalmanAngle Calculation (object has no attribute)

### ISSUE THREAD

**Issue by jimtal001** [tkurbad/mipSIE#1]
in the function: **_calculateKalmanAngle(...):**

For X-axis:
you are passing the parameter: **self.kalmanx**  
When I run the library I get the error:
**object has no attribute 'kalmanx'**

jimtal001@gmail.com

**Comment by tkurbad** [comment]
Please read the repository description. This is just a collection of (probably incomplete and/or not working) code snippets to test some ideas of mine. They are not meant to be usable by others, and by no means is this production ready code to program a robot.
